spring.application.name=dto-service

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/armaan_schema
spring.datasource.username=root
spring.datasource.password=VMware1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Swagger Properties to disable in PROD::
#SpringDoc /v3/api-docs endpoint is enabled by default. To disable it in production
#springdoc.api-docs.enabled=false

#SpringDoc /swagger-ui.html endpoint is enabled by default. To disable it in production
#springdoc.swagger-ui.enabled=false
